@startuml

cloud Client {
    component Browser
}

node Application {
    component WebUI AS "Web UI"
    component WebAPI AS "Web API"
}

node Database {
    database Orders
}

cloud {
    component CRIMS_API AS "CRIMS API"
}

Browser -- WebUI
WebAPI -- Orders
WebAPI -- CRIMS_API
WebUI -- WebAPI

@enduml