@startuml

cloud Client {
    component Browser
}

node Application {
    component WebUI AS "Web UI"
}

node Database {
    database Orders
}

cloud {
    component CRIMS_API AS "CRIMS API"
}

Browser -- WebUI
WebUI -- Orders
WebUI -- CRIMS_API

@enduml